# Generated by Django 4.2.3 on 2023-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, null=True)),
                ('author', models.CharField(max_length=140, null=True)),
                ('price', models.FloatField(null=True)),
                ('category', models.CharField(choices=[('Horror', 'Horror'), ('Fantasy', 'Fantasy'), ('Classic', 'Classic'), ('Comics', 'Comics')], max_length=120, null=True)),
                ('description', models.TextField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Cancelled'), ('Delivered', 'Delivered'), ('in progress', 'in progress'), ('Out of Order', 'Out of Order'), ('Cancelled', 'Cancelled')], max_length=60, null=True)),
            ],
        ),
    ]
